module.exports = {
    COMMAND_NONE: 0,
    COMMAND_TRANSFER: 1,

    OPERATION_NONE: 0,
    OPERATION_MAIN: 1,
    OPERATION_SHARD: 2,
    OPERATION_BASE: 3,
    OPERATION_SPAWNING: 4,
    OPERATION_FILLING: 5,
    OPERATION_UPGRADING: 6,
    OPERATION_BUILDING: 7,
    OPERATION_CREEP: 8,
    OPERATION_MAX:8,

    ROLE_NONE:  0,
    ROLE_FILLER: 1,
    ROLE_UPGRADER: 2,
    ROLE_BUILDER: 3,

}
